# Generated by Django 5.0.1 on 2024-01-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='address',
            field=models.CharField(default=123, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
