# Generated by Django 5.0.1 on 2024-01-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_object_address_alter_object_lat_alter_object_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='marker',
            field=models.ImageField(default=123, upload_to='markers/'),
            preserve_default=False,
        ),
    ]
